### ISSUE TITLE
wholebodydynamics device does not compile if iDynTree CMake option IDYNTREE_USES_ICUB_MAIN is OFF

### ISSUE THREAD

**Issue by prashanthr05** [robotology/whole-body-estimators#46]
For a report on this, please see https://github.com/prashanthr05/whole-body-estimators/runs/506344138?check_suite_focus=true#step:12:97.

This needs to be documented in the [Dependencies section](https://github.com/robotology/whole-body-estimators/blob/master/README.md#page_facing_up-dependencies) of README.md.

**Comment by traversaro** [comment]
Yes, that is definitely inconvenient. My plan was to transform some simple conversions utility that we have in iDynTree in header only libraries, so that we can always install them, and then it is left to the downstream projects to find the dependencies. I could not find a place where to track that, so I created a new issue in https://github.com/robotology/idyntree/issues/653 .

**Comment by prashanthr05** [comment]
The README was updated. Closing this issue.
